### ISSUE TITLE
Status of the GIT repository

### ISSUE THREAD

**Issue by watzo** [watzo/aksy#1]
Hi there!

I am the original author of Aksy, and was thinking of migrating it to Github and reviving the project a bit as ak.sys is now really obsolete..

Did you do some work on this repository or is it a verbatim copy of the HG repository at Google code?

Thanks!

Regards
Walco

**Comment by svanzoest** [comment]
hi there @watzo 
It is basically verbatim. I never found the time to really do much more other than play with what you had and I didn't want loose access to it or even forget about where it came from so I could give proper credit. :) I still use it to work with my Akai Z8.

**Comment by watzo** [comment]
Hi

Great! I think I will fork it to continue working on it. I tried to git svn clone the original source repository but this process is quite cumbersome probably because the svn repository is so old.

Regards
Walco

**Comment by svanzoest** [comment]
I can transfer it to you if you want.

**Comment by watzo** [comment]
That would be awesome!

**Comment by svanzoest** [comment]
done! Let me know if you run into any issues.

**Comment by watzo** [comment]
Thanks! It worked - welcome as collaborator ;-)
